openapi: 3.0.0
info:
  title: TweetYoink Server Response Format
  version: 1.2.0
  description: |
    API contract for TweetYoink server responses.

    **Version 1.2.0 Changes (Feature 008)**:
    - Added optional `title` field to ResponseContentItem (all types)
    - Added new "debug" content type for JSON object display
    - Extended `content` field to support object type for debug content

    **Backward Compatibility**: All v1.1.0 responses remain valid v1.2.0 responses.
    The title field is optional, and debug type is additive alongside existing types.

servers:
  - url: http://localhost:3000
    description: Local development server

paths:
  /:
    post:
      summary: Submit tweet data for processing
      description: |
        Primary endpoint for tweet capture data. Can return either synchronous
        results or initiate async processing.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TweetData'
      responses:
        '200':
          description: Successful submission
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostResponse'

  /status:
    post:
      summary: Check async request status
      description: Poll this endpoint to check status of async requests
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - requestId
              properties:
                requestId:
                  type: string
                  description: Request ID returned from initial POST
      responses:
        '200':
          description: Status information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostResponse'

components:
  schemas:
    TweetData:
      type: object
      description: Tweet capture data sent to server (unchanged from v1.1.0)

    ResponseContentItem:
      type: object
      required:
        - type
        - content
      properties:
        type:
          type: string
          enum: [text, image, debug, link, unknown]
          description: |
            Content type identifier. Determines how the extension renders the item.
            - "text": Plain text content (rendered via textContent - XSS safe)
            - "image": Image URL (future support)
            - "debug": JSON object (NEW in v1.2.0 - formatted with 2-space indent)
            - "link": Hyperlink URL (future support)
            - Other values: Gracefully ignored by extension
        content:
          oneOf:
            - type: string
              description: For text, image, link types
            - type: object
              description: For debug type - any JSON-serializable object
          description: |
            Content payload. Interpretation depends on type:
            - type="text": Plain text string to display
            - type="image": Image URL (future)
            - type="debug": JSON object to format and display (NEW in v1.2.0)
            - type="link": Hyperlink URL (future)
        title:
          type: string
          description: |
            **NEW in v1.2.0**: Optional title displayed above content.
            Applies to all content types (text, image, debug, link).
            If present and non-empty, renders as bold header above content block.
            If empty or missing, no title header is shown.
        metadata:
          type: object
          additionalProperties: true
          description: |
            Optional metadata for future extensions.
            Examples: timestamp, confidence, etc.

            **Deprecation Note**: metadata.title from v1.1.0 is deprecated
            in favor of top-level title field.

      example:
        type: text
        title: "Sentiment Analysis"
        content: "This tweet demonstrates positive sentiment (95% confidence)"
        metadata:
          confidence: 0.95
          timestamp: "2025-11-01T12:00:00Z"

    PostResponse:
      oneOf:
        - $ref: '#/components/schemas/SyncResponse'
        - $ref: '#/components/schemas/AsyncResponse'
        - $ref: '#/components/schemas/ErrorResponse'

    SyncResponse:
      type: object
      required:
        - status
        - result
      properties:
        status:
          type: string
          enum: [completed]
          description: Indicates synchronous processing completed
        result:
          oneOf:
            - type: array
              items:
                $ref: '#/components/schemas/ResponseContentItem'
              description: |
                **Recommended format** for overlay support.
                Array of content items that will be displayed in overlay.
            - type: object
              description: |
                **Legacy format** (backward compatible).
                Extension logs to console but does not display in overlay.

      example:
        status: completed
        result:
          - type: text
            title: "Analysis Summary"
            content: "Positive sentiment detected with high confidence"
          - type: debug
            title: "Processing Details"
            content:
              model: "gpt-4"
              processing_time_ms: 826
              confidence: 0.95

    AsyncResponse:
      type: object
      required:
        - status
        - requestId
      properties:
        status:
          type: string
          enum: [pending, processing]
          description: |
            Async processing status
            - "pending": Queued but not started
            - "processing": Currently being processed
        requestId:
          type: string
          description: Unique ID for status polling
        estimatedDuration:
          type: number
          description: Estimated completion time in seconds (optional)
        progress:
          type: number
          minimum: 0
          maximum: 1
          description: Processing progress (0.0 to 1.0, optional)
        message:
          type: string
          description: Human-readable status message (optional)

      example:
        status: processing
        requestId: "req_1698576000_abc123"
        estimatedDuration: 30
        progress: 0.65
        message: "Processing tweet analysis..."

    ErrorResponse:
      type: object
      required:
        - status
        - error
      properties:
        status:
          type: string
          enum: [error, failed]
          description: Indicates processing failed
        error:
          type: object
          required:
            - code
            - message
          properties:
            code:
              type: string
              description: Machine-readable error code
              examples:
                - PARSE_ERROR
                - RATE_LIMIT_EXCEEDED
                - AUTHENTICATION_FAILED
            message:
              type: string
              description: Human-readable error message

      example:
        status: error
        error:
          code: "RATE_LIMIT_EXCEEDED"
          message: "Rate limit exceeded. Try again in 60 seconds."

  examples:
    SyncWithTitlesAndDebug:
      summary: Sync response with titles and debug content (v1.2.0)
      description: Server returns immediately with titled items and debug JSON
      value:
        status: completed
        result:
          - type: text
            title: "Sentiment Analysis"
            content: "Positive (confidence: 95%)"
          - type: text
            title: "Key Topics"
            content: "AI, machine learning, technology"
          - type: debug
            title: "Processing Metrics"
            content:
              total_time_ms: 826
              model: "gpt-4"
              tokens_used: 1234
              stages: ["sentiment", "topics", "entities"]

    BackwardCompatibleV11:
      summary: Backward compatible response (v1.1.0 format)
      description: Existing v1.1.0 responses work without changes
      value:
        status: completed
        result:
          - type: text
            content: "Analysis: This tweet shows positive sentiment"
          - type: text
            content: "Detected topics: technology, AI, innovation"

    DebugOnlyResponse:
      summary: Debug-only response for development
      description: Useful for inspecting raw processing data
      value:
        status: completed
        result:
          - type: debug
            title: "Full Analysis Results"
            content:
              sentiment:
                score: 0.95
                label: "positive"
                confidence: 0.98
              entities:
                - text: "AI"
                  type: "technology"
                  confidence: 0.98
                - text: "innovation"
                  type: "concept"
                  confidence: 0.87
              topics: ["technology", "ai", "future"]
              metadata:
                processing_time: "826ms"
                model: "gpt-4"

    MixedTitledUntitled:
      summary: Mixed titled and untitled content
      description: Some items have titles, others don't (backward compatible)
      value:
        status: completed
        result:
          - type: text
            title: "Summary"
            content: "Main findings from analysis"
          - type: text
            content: "Additional notes without title"
          - type: debug
            title: "Debug Info"
            content:
              version: "1.2.0"
              timestamp: "2025-11-01T12:00:00Z"

notes:
  - |
    **Feature 008 Enhancements (v1.2.0)**:
    - All content types (text, image, debug, link) can now have optional title field
    - New "debug" content type displays JSON objects with 2-space indentation and monospace font
    - Titles render as bold headers above content for better organization
    - 100% backward compatible - title is optional, existing responses work unchanged

  - |
    **Title Usage Guidelines**:
    - Keep titles concise (recommended: <50 characters)
    - Use sentence case or title case
    - Titles help users quickly scan multiple content items
    - Empty/whitespace-only titles are treated as missing (no header rendered)

  - |
    **Debug Type Guidelines**:
    - Use for structured technical data, processing metrics, raw analysis results
    - Content must be JSON-serializable (no functions, circular refs, symbols)
    - Recommended max size: 50KB (larger JSON may impact performance)
    - Useful for development, troubleshooting, and power users

  - |
    **Backward Compatibility**:
    - v1.1.0 servers continue to work without modifications
    - Gradual adoption: add title field to existing items incrementally
    - Add debug items alongside existing text items
    - No breaking changes, no forced migration

  - |
    **Content Safety**:
    - Extension uses `textContent` for rendering titles and text, not `innerHTML`
    - Debug JSON rendered as formatted text (XSS-safe)
    - Server does not need to sanitize content - extension handles XSS protection

  - |
    **Performance Recommendations**:
    - Keep array length ≤ 20 items for optimal UX (extension supports up to 50)
    - Keep text content ≤ 1000 characters per item for readability
    - Keep debug JSON ≤ 50KB for performance (warning shown above this)
    - Use title field to provide context without bloating content
